# Generated by Django 3.0.3 on 2020-03-08 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('time_created', models.BigIntegerField(default=1583682373)),
                ('time_modified', models.BigIntegerField(default=1583682373)),
                ('role', models.ManyToManyField(related_name='user_role', to='role.RoleModel')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
