# Generated by Django 3.0.3 on 2020-03-08 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('time_created', models.BigIntegerField(default=1583682373)),
                ('time_modified', models.BigIntegerField(default=1583682373)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
    ]
